version: '3'
services:
  auth-db:
    image: postgres
    container_name: auth-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
  
  auth-api:
    build: "./auth-api"
    container_name: auth-api
    restart: always
    env_file:
      - ./auth-api/.env
    ports:
      - 3000:3000
    depends_on:
      - auth-db
  
  product-db:
    image: postgres
    container_name: product-db
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product
  
  product-api:
    build: "./product-api"
    container_name: product-api
    restart: always
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    depends_on:
      - product-db
  
  sales-db:
    image: mongo
    container_name: sales-db
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=sales

  sales-api:
    build: "./sales-api"
    container_name: sales-api
    restart: always
    env_file:
      - ./sales-api/.env
    ports:
      - 3001:3001
    depends_on:
      - sales-db

  sales-rabbitmq:
    image: rabbitmq:3-management
    container_name: sales-rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest